# vivid_arts_toolbox/vivid_painter_export.py
import json
import shutil
import subprocess
from pathlib import Path
import bpy

# ---------- helpers ----------

def _addon_dir() -> Path:
    return Path(__file__).resolve().parent

def _find_optimized_obj(context) -> bpy.types.Object:
    obj = context.active_object
    if obj and obj.type == 'MESH' and obj.name.endswith("_Optimized"):
        return obj
    for o in context.scene.objects:
        if o.type == 'MESH' and o.name.endswith("_Optimized"):
            return o
    raise RuntimeError("No *_Optimized mesh found in the scene.")

def _derive_names(o: bpy.types.Object):
    base = o.name[:-10] if o.name.endswith("_Optimized") else o.name
    return base, f"{base}_Optimized"

def _project_dirs():
    blend_path = Path(bpy.data.filepath)
    if not blend_path:
        raise RuntimeError("Please save your .blend file first.")
    proj_dir = blend_path.parent
    bake_mesh = proj_dir / "BakeMesh"
    bake_textures = proj_dir / "BakeTextures"
    return proj_dir, bake_mesh, bake_textures

def _expect_file(p: Path, what: str):
    if not p.exists():
        raise RuntimeError(f"Couldn't find {what}: {p}")

def _copy_starter_spp(dst_spp: Path) -> Path:
    starter = _addon_dir() / "VIVID_Arts.spp"
    _expect_file(starter, "starter SPP (VIVID_Arts.spp) inside addon")
    shutil.copy2(starter, dst_spp)
    return dst_spp

def _template_path(is_surface: bool) -> Path:
    tmpl = "VIVID_Arts_Surface.spexp" if is_surface else "VIVID_Arts.spexp"
    p = _addon_dir() / tmpl
    _expect_file(p, f"export template {tmpl} inside addon")
    return p

# ---------- painter bootstrap ----------

def _build_painter_bootstrap_py(config: dict, out_path: Path):
    code = f'''# Auto-generated by VIVID Arts Toolbox
import json, traceback
from pathlib import Path
try:
    import substance_painter
    from substance_painter import project, resources, export, texturing
except Exception as e:
    print("[VIVID] Failed to import Painter Python API:", e)
    raise

cfg = {json.dumps(config, indent=2)}

def warn(msg): print("[VIVID][WARN]", msg)
def info(msg): print("[VIVID]", msg)

def _first_texture_set():
    stacks = texturing.list_texture_sets()
    if not stacks:
        raise RuntimeError("No texture sets found in project.")
    return stacks[0]

def _find_layer_by_name(stack, name):
    for r in texturing.list_layers(stack):
        if r.name == name:
            return r
    return None

def _import_or_get_resource(file_path: str):
    p = Path(file_path)
    if not p.exists():
        warn(f"Missing texture: {{p.name}}")
        return None
    try:
        rid = resources.import_project_resource(str(p))
        return rid
    except Exception as e:
        warn(f"Could not import resource {{p.name}}: {{e}}")
        return None

def _assign_channel_from_texture(layer, channel_id: str, tex_path: str, normal_format=None):
    rid = _import_or_get_resource(tex_path)
    if rid is None:
        return
    try:
        fill = texturing.create_fill_layer(layer, channel_id)
        texturing.set_fill_layer_resource(fill, channel_id, rid)
        if normal_format and channel_id in ("normal", "coat_normal"):
            project.set_normal_map_format(project.NormalMapFormat.OPENGL)
    except Exception as e:
        warn(f"Failed assigning {{channel_id}} from {{tex_path}}: {{e}}")

def main():
    prj_path = Path(cfg["spp_path"])
    info(f"Opening project: {{prj_path}}")
    project.open(str(prj_path))

    mesh = Path(cfg["fbx_path"])
    if not mesh.exists():
        raise RuntimeError(f"FBX not found: {{mesh}}")
    info(f"Setting mesh: {{mesh}}")
    project.set_mesh(str(mesh))

    base_mat_name = cfg["material_name"]
    stack = _first_texture_set()
    try:
        texturing.rename_texture_set(stack, base_mat_name)
    except Exception as e:
        warn(f"Couldn't rename texture set: {{e}}")

    layer_map = {{
        "Base": cfg["layers"]["Base"],
        "Lit": cfg["layers"]["Lit"],
        "AO_Wide": cfg["layers"]["AO_Wide"],
        "AO_Roughness": cfg["layers"]["AO_Roughness"],
    }}
    for lname, channels in layer_map.items():
        layer = _find_layer_by_name(stack, lname)
        if layer is None:
            warn(f"Missing layer in SPP: {{lname}}")
            continue
        for chan, entry in channels.items():
            if isinstance(entry, dict) and entry.get("kind") == "mask_fill":
                m = texturing.create_black_mask(layer)
                rid = _import_or_get_resource(entry["path"])
                if rid:
                    fill = texturing.create_fill_layer(m, "grayscale")
                    texturing.set_fill_layer_resource(fill, "grayscale", rid)
                continue
            tex_path = entry["path"]
            normal_fmt = entry.get("normal_format")
            _assign_channel_from_texture(layer, chan, tex_path, normal_format=normal_fmt)

    template_path = Path(cfg["export"]["template"])
    if template_path.exists():
        try:
            export.set_export_presets([str(template_path)])
            export.set_current_preset(template_path.stem)
        except Exception as e:
            warn(f"Failed to set export template: {{e}}")
    else:
        warn(f"Template missing: {{template_path}}")

    out_dir = Path(cfg["export"]["output_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)
    try:
        export.set_export_path(str(out_dir))
    except Exception as e:
        warn(f"Failed to set export path: {{e}}")

    size = int(cfg["export"]["size"])
    try:
        export.set_size_export(size)
    except Exception as e:
        warn(f"Failed to set export size: {{e}}")

    project.save()
    info("Done.")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        traceback.print_exc()
        raise
'''
    out_path.write_text(code, encoding="utf-8")

# ---------- main entry ----------

def run_export(context,
               painter_exe: str,
               texture_export_dir: str,
               texture_res: int,
               is_surface: bool,
               open_after: bool) -> str:

    opt_obj = _find_optimized_obj(context)
    base_name, _ = _derive_names(opt_obj)
    proj_dir, bake_mesh, bake_textures = _project_dirs()

    fbx_path = bake_mesh / f"{base_name}_Optimized.fbx"
    _expect_file(fbx_path, "Optimized FBX in BakeMesh")

    dst_spp = proj_dir / f"{base_name}.spp"
    _copy_starter_spp(dst_spp)

    # Only import these textures
    tex = {
        "DLBC":         bake_textures / f"{base_name}_DLBC.png",
        "Delit":        bake_textures / f"{base_name}_Delit.png",
        "DLAO":         bake_textures / f"{base_name}_DLAO.png",
        "Occlusion":    bake_textures / f"{base_name}_Occlusion.png",
        "Bent_Normals": bake_textures / f"{base_name}_Bent_Normals.png",
        "Heightmap":    bake_textures / f"{base_name}_Heightmap.png",
        "Normals":      bake_textures / f"{base_name}_Normals.png",
    }

    template = _template_path(is_surface)

    cfg = {
        "spp_path": str(dst_spp),
        "fbx_path": str(fbx_path),
        "material_name": base_name,
        "layers": {
            "Base": {
                "base_color":         {"path": str(tex["Delit"])},
                "roughness":          {"path": str(tex["Delit"])},
                "normal":             {"path": str(tex["Normals"]),      "normal_format": "OpenGL"},
                "ambient_occlusion":  {"path": str(tex["Occlusion"])},
                "coat_normal":        {"path": str(tex["Bent_Normals"]), "normal_format": "OpenGL"},
                "height":             {"path": str(tex["Heightmap"])},
            },
            "Lit": {
                "base_color":         {"path": str(tex["DLBC"])},
            },
            "AO_Wide": {
                "ambient_occlusion":  {"path": str(tex["DLAO"])},
            },
            "AO_Roughness": {
                "mask": {"kind": "mask_fill", "path": str(tex["Occlusion"])},
            },
        },
        "export": {
            "template":  str(template),
            "output_dir": str(Path(texture_export_dir) if texture_export_dir else (proj_dir / "PainterExports")),
            "size": int(texture_res),
        },
    }

    bootstrap_py = proj_dir / f"vivid_painter_bootstrap_{base_name}.py"
    _build_painter_bootstrap_py(cfg, bootstrap_py)

    if open_after:
        painter_path = Path(painter_exe) if painter_exe else None
        if not (painter_path and painter_path.exists()):
            return (f"SPP prepared at '{dst_spp.name}'. Painter EXE not set; "
                    f"open Painter 11.0.2 manually and run: {bootstrap_py.name}")
        cmd = [str(painter_path), str(dst_spp), "--enable-py", "--python-script", str(bootstrap_py)]
        try:
            subprocess.Popen(cmd)
            return "SPP prepared and Painter launch attempted."
        except Exception as e:
            return f"SPP prepared but failed to launch Painter automatically: {e}"
    else:
        return f"SPP prepared at '{dst_spp.name}'. Launch skipped."

